flowapp-mysql:
  image: mysql:5.7
  container_name: flowapp-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=pass
  volumes:
      - ./_mysql/:/var/lib/mysql
  ports:
   - "3306:3306"

flowapp-webserver:
  image: phpdockerio/nginx:latest
  container_name: flowapp-webserver
  volumes:
      - ./_public/:/var/www/flowapp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  links:
   - flowapp-php-fpm

flowapp-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: flowapp-php-fpm
  volumes:
    - ./_public/:/var/www/flowapp
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - flowapp-mysql
